.\"%W	%G
.TH libpar 3  "19 January 2000"
.SH NAME
libpar \- provides functions to retrieve parameters.
.SH DESCRIPTION
This library provides functions to (1) Retrieve runtime parameters from the
environment, command line, and input files in a uniform way, and (2) Extract
parameters from arbitrary strings.  The first provides a mechanism for sharing
system-wide configuration information, and the second is convenient for
interpreting IPC messages. 

The components include:

.TP 15
.B setpar:
Parses the the environment, command line, and any files that are designated on
the command line, i.e.
.I par=filename,
and builds an internal table of parameter names
and values.  
.TP 15
.B getpar:
Retrieves from the internal parameter table the value of a named parameter
interpreted according to an specified format. 
.TP 15
.B mstpar:
Retrieves from the internal parameter table the value of a named parameter
interpreted according to an specified format.  If the parameter is missing, the
functions calls exit(), terminating the program.
.TP 15
.B endpar:
Cleans up memory associated with the internal parameter tables.
.TP 15
.B setarg:
Parses an arbitrary input string for parameters and builds an internal table of
parameter names and values. 
.TP 15
.B getarg:
Retrieves from the internal parameter table the value of a named parameter
interpreted according to an specified format. 
.TP 15
.B endarg:
Cleans up memory associated with the internal parameter tables.

.PP
.SH "SEE ALSO"
.BR getarg (3),
.BR getopt (3C),
.BR getpar (3)

