.TH libcancomp 3 "01 September 2000"
.SH NAME

canada_compress, canada_uncompress \- compress/uncompress waveforms using the CNSN compression algorithm

.SH SYNOPSIS
.nf
.ta 8 16 24 32
#include "canada_compress.h"

int
canada_compress(comp, uncomp, bytes, samples, v0)
char    \(**comp;
int32_t \(**uncomp;
int     \(**bytes;
int     samples;
int32_t \(**v0;

int
canada_uncompress(comp, uncomp, bytes, samples, v0)
char    \(**comp;
int32_t \(**uncomp;
int     \(**bytes;
int     samples;
int32_t \(**v0;
.fi

.SH MT_LEVEL
Safe

.SH DESCRIPTION
These functions compress and uncompress waveforms according to the 
compression algorithm used by the Canadian National Seismograph Network.
\fIcanada_compress\fP(\|) implements compression. It reads \fIsamples\fP
values from \fIuncomp\fP, computes compressed bytes and stores them in
\fIcomp\fP. Note that \fIsamples\fP must be evenly divisible by 20.
\fIcanada_compress\fP(\|) returns the number of compressed bytes in
\fIbytes\fP. \fIv0\fP is required - it is used as the last value in the 
compressed sequence (the extra value is required for differencing).
In the Canadian implementation of the algorithm, v0 is always the 
first value of the next data sequence.

\fIcanada_uncompress\fP(\|) takes exactly the same arguments. In this 
case, it reads bytes from \fIcomp\fP as needed to generate \fIsamples\fP
number of values in \fIuncomp\fP. Note that the value for \fIsamples\fP 
passed to \fIcanada_uncompress\fP(\|) must be exactly what was originally 
passed to \fIcanada_compress\fP(\|) or decompression will fail. 
\fIcanada_uncompress\fP(\|) will not allow more than \fIbytes\fP bytes of
\fIcomp\fP to be used to generate \fIuncomp\fP. It also returns the actual 
number of bytes accessed through \fIbytes\fP and the last value of the series 
through \fIv0\fP (which may be disregarded or used as an error check).

.SH ARGUMENTS
.TP 10
comp
Character buffer containing compressed data.

.TP 10
uncomp
int32_t integer buffer containing uncompressed data.

.TP 10
bytes
Number of bytes ised in \fIcomp\fP.

.TP 10
samples
Number of samples used in \fIuncomp\fP.

.TP 10
v0
First value of the NEXT sequence.

.SH RETURN VALUES
The following values may be returned to the calling program.
.TP 10
CANCOMP_ERR	
An unrecoverable error was encountered (malloc failure).

.TP 10
CANCOMP_SUCCESS	
No errors were encountered.

.TP 10
CANCOMP_NOT_20
\fIsamples\fP not divisible by 20

.TP 10
CANCOMP_CORRUPT
a corrupt call occurred

.TP 10
CANCOMP_EXCEED
number of bytes required to generate uncompressed data exceeds 
supplied bytes

.SH EXAMPLES
The following is an example of how to use the function(s).
.nf
.ta 8 16 24 32

	#include "canada_compress.h"
.fi

.SH DIAGNOSTICS

.SH X RESOURCES
X resources are not applicable to this program.

.SH ENVIRONMENT 
No environment variables are used by the library.

.SH DATABASE
No database resources are used with this library.

.SH LIBRARIES
This library is not dependant on any other libraries.

.SH FILES
No other files are used or generated by the library.

.SH SEE ALSO

Beverley, K.I.,"Canadian National Seismograph Network Communication Protocol",
Geophysics Division, Geological Survey of Canada, Department of Energy,
Mines and Resources, Ottawa, Canada, August 9, 1990.

.SH AUTHOR
.br
R. Stead, SAIC Monitoring Systems Operation, CMR, Arlington, VA


