#ifndef _MOTIF_DEFS_H
#define _MOTIF_DEFS_H

class ActionEvent;
class Application;
class ArrowButton;
class Button;
class Choice;
class Component;
class FileChoice;
class FileDialog;
class FileSelectionBox;
class Form;
class FormDialog;
class Frame;
class Gobject;
class InfoArea;
class IPCClient;
class Label;
class List;
class MainWindow;
class Menu;
class MenuBar;
class MessageDialog;
class Pane;
class ParamDialog;
class PlugInManager;
class PopupMenu;
class Question;
class RadioBox;
class RowColumn;
class Scale;
class ScrollBar;
class ScrolledPane;
class ScrolledWindow;
class Separator;
class Space;
class StatusDialog;
class TextDialog;
class TextField;
class TextQuestion;
class Toggle;
class ToolBar;
class TopWindow;
class UndoAction;
class UndoButton;
class UndoManager;
class Warn;
class Warnings;

#endif
