/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_ar_info.h
 *
 * SYNOPSIS
 *    The "Ar_Info" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_AR_INFO_H
#define DB_AR_INFO_H


/*
 *  The query used to create the "Ar_Info" structures:
 *       SELECT * from ar_info
 *
 */
typedef struct ar_info {
	long	orid;
	long	arid;
	long	time_error_code;
	long	az_error_code;
	long	slow_error_code;
	long	src_dpnt_corr_type;
	char	vmodel[16];
	double	total_travel_time;
	double	tt_table_value;
	double	ellip_corr;
	double	elev_corr;
	double	bulk_static_sta_corr;
	double	src_dpnt_corr;
	double	model_error;
	double	meas_error;
	double	model_plus_meas_error;
	double	time_import;
	double	az_import;
	double	slow_import;
	double	slow_vec_res;
	char	lddate[18];
}Ar_Info;

#endif /* DB_AR_INFO_H */
