/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_arrival.h
 *
 * SYNOPSIS
 *    The "Arrival" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_ARRIVAL_H
#define DB_ARRIVAL_H


/*
 *  The query used to create the "Arrival" structures:
 *       SELECT * from arrival
 *
 */
typedef struct arrival {
	char	sta[7];
	double	time;
	long	arid;
	long	jdate;
	long	stassid;
	long	chanid;
	char	chan[9];
	char	iphase[9];
	char	stype[2];
	double	deltim;
	double	azimuth;
	double	delaz;
	double	slow;
	double	delslo;
	double	ema;
	double	rect;
	double	amp;
	double	per;
	double	logat;
	char	clip[2];
	char	fm[3];
	double	snr;
	char	qual[2];
	char	auth[16];
	long	commid;
	char	lddate[18];
}Arrival;

#endif /* DB_ARRIVAL_H */
