/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_amplitude.h
 *
 * SYNOPSIS
 *    The "Amplitude" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_AMPLITUDE_H
#define DB_AMPLITUDE_H


/*
 *  The query used to create the "Amplitude" structures:
 *       SELECT * from amplitude
 *
 */
typedef struct amplitude {
	long	ampid;
	long	arid;
	long	parid;
	char	chan[9];
	double	amp;
	double	per;
	double	snr;
	double	amptime;
	double	start_time;
	double	duration;
	double	bandw;
	char	amptype[9];
	char	units[16];
	char	clip[2];
	char	inarrival[2];
	char	auth[16];
	char	lddate[18];
}Amplitude;

#endif /* DB_AMPLITUDE_H */
