/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_assoc.h
 *
 * SYNOPSIS
 *    The "Assoc" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_ASSOC_H
#define DB_ASSOC_H


/*
 *  The query used to create the "Assoc" structures:
 *       SELECT * from assoc
 *
 */
typedef struct assoc {
	long	arid;
	long	orid;
	char	sta[7];
	char	phase[9];
	double	belief;
	double	delta;
	double	seaz;
	double	esaz;
	double	timeres;
	char	timedef[2];
	double	azres;
	char	azdef[2];
	double	slores;
	char	slodef[2];
	double	emares;
	double	wgt;
	char	vmodel[16];
	long	commid;
	char	lddate[18];
}Assoc;

#endif /* DB_ASSOC_H */
