/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_netmag.h
 *
 * SYNOPSIS
 *    The "Netmag" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_NETMAG_H
#define DB_NETMAG_H


/*
 *  The query used to create the "Netmag" structures:
 *       SELECT * from netmag
 *
 */
typedef struct netmag {
	long	magid;
	char	net[9];
	long	orid;
	long	evid;
	char	magtype[7];
	long	nsta;
	double	magnitude;
	double	uncertainty;
	char	auth[16];
	long	commid;
	char	lddate[18];
}Netmag;

#endif /* DB_NETMAG_H */
