/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_origerr.h
 *
 * SYNOPSIS
 *    The "Origerr" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_ORIGERR_H
#define DB_ORIGERR_H


/*
 *  The query used to create the "Origerr" structures:
 *       SELECT * from origerr
 *
 */
typedef struct origerr {
	long	orid;
	double	sxx;
	double	syy;
	double	szz;
	double	stt;
	double	sxy;
	double	sxz;
	double	syz;
	double	stx;
	double	sty;
	double	stz;
	double	sdobs;
	double	smajax;
	double	sminax;
	double	strike;
	double	sdepth;
	double	stime;
	double	conf;
	long	commid;
	char	lddate[18];
}Origerr;

#endif /* DB_ORIGERR_H */
