/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_stamag.h
 *
 * SYNOPSIS
 *    The "Stamag" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_STAMAG_H
#define DB_STAMAG_H


/*
 *  The query used to create the "Stamag" structures:
 *       SELECT * from stamag
 *
 */
typedef struct stamag {
	long	magid;
	long	ampid;
	char	sta[7];
	long	arid;
	long	orid;
	long	evid;
	char	phase[9];
	double	delta;
	char	magtype[7];
	double	magnitude;
	double	uncertainty;
	double	magres;
	char	magdef[2];
	char	mmodel[16];
	long	commid;
	char	auth[16];
	char	lddate[18];
}Stamag;

#endif /* DB_STAMAG_H */
