/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_site.h
 *
 * SYNOPSIS
 *    The "Site" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_SITE_H
#define DB_SITE_H

/*
 *  The query used to create the "Site" structures:
 *       SELECT * from site
 *
 */
typedef struct site {
	char	sta[7];
	long	ondate;
	long	offdate;
	double	lat;
	double	lon;
	double	elev;
	char	staname[51];
	char	statype[5];
	char	refsta[7];
	double	dnorth;
	double	deast;
	char	lddate[18];
}Site;

#endif /* DB_SITE_H */
