/*
 *    Copyright (c) 1993-1997 Science Applications International Corporation.
 */

/*
 * NAME
 *    db_wfdisc.h
 *
 * SYNOPSIS
 *    The "Wfdisc" structure to be used with the GDI Array Structs.
 *
 * AUTHOR
 *    Generated by gdi_gen_Astructs 110.2 08/20/97.
 *
 */

#ifndef DB_WFDISC_H
#define DB_WFDISC_H


/*
 *  The query used to create the "Wfdisc" structures:
 *       SELECT * from wfdisc
 *
 */
typedef struct wfdisc {
	char	sta[7];
	char	chan[9];
	double	time;
	long	wfid;
	long	chanid;
	long	jdate;
	double	endtime;
	long	nsamp;
	double	samprate;
	double	calib;
	double	calper;
	char	instype[7];
	char	segtype[2];
	char	datatype[3];
	char	clip[2];
	char	dir[65];
	char	dfile[33];
	long	foff;
	long	commid;
	char	lddate[18];
}Wfdisc;

#endif /* DB_WFDISC_H */
